; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2 on Fri Mar 01 2019 21:07:09 GMT-0800 (Pacific Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


