; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2 on Fri Mar 01 2019 21:07:11 GMT-0800 (Pacific Standard Time)

M116 P0       ; Wait for set temperatures to be reached
M703          ; Recall configuration for last used filament
